// Auto-generated by translate-gemini.js. KHÔNG sửa tay — chỉnh strings/*.json rồi chạy lại.
window.WIDGET_TRANSLATIONS = {
  "971 45 443<br> &nbsp;": {
    "en": "971 45 443<br> &nbsp;",
    "vi": "971 45 443<br> &nbsp;",
    "no": "971 45 443<br> &nbsp;"
  },
  "<b>Address</b><br> Ravnåsveien 3<br> 1254 Oslo": {
    "en": "<b>Address</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "vi": "<b>Địa chỉ</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "no": "<b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo"
  },
  "<b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo": {
    "en": "<b>Address</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "vi": "<b>Địa chỉ</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "no": "<b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo"
  },
  "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;": {
    "en": "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;",
    "vi": "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;",
    "no": "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;"
  },
  "<span>Artikkel</span><span>Artikkel</span>": {
    "en": "ArticleArticle",
    "vi": "Bài viếtBài viết",
    "no": "ArtikkelArtikkel"
  },
  "<span>Tilgjengelige roller</span>": {
    "en": "Available roles",
    "vi": "Các vai trò có sẵn",
    "no": "Tilgjengelige roller"
  },
  "ABOUT US": {
    "en": "ABOUT US",
    "vi": "VỀ CHÚNG TÔI",
    "no": "OM OSS"
  },
  "About Us": {
    "en": "About Us",
    "vi": "Về chúng tôi",
    "no": "Om oss"
  },
  "Account number: 1503.02.07693": {
    "en": "Account number: 1503.02.07693",
    "vi": "Số tài khoản: 1503.02.07693",
    "no": "Kontonummer: 1503.02.07693"
  },
  "Activities": {
    "en": "Activities",
    "vi": "Hoạt động",
    "no": "Aktiviteter"
  },
  "Administrator": {
    "en": "Administrator",
    "vi": "Quản trị viên",
    "no": "Administrator"
  },
  "Artikkel": {
    "en": "Article",
    "vi": "Bài viết",
    "no": "Artikkel"
  },
  "Baptistmenigheten i Oslo": {
    "en": "The Baptist Congregation in Oslo",
    "vi": "Việt Nam tại Oslo",
    "no": "Baptistmenigheten i Oslo"
  },
  "Barn": {
    "en": "Children",
    "vi": "Trẻ em",
    "no": "Barn"
  },
  "Betaling": {
    "en": "Payment",
    "vi": "Thanh toán",
    "no": "Betaling"
  },
  "Bibelskole": {
    "en": "Bible School",
    "vi": "Trường Kinh Thánh",
    "no": "Bibelskole"
  },
  "Bilde": {
    "en": "Image",
    "vi": "Hình ảnh",
    "no": "Bilde"
  },
  "Bli med": {
    "en": "Join us",
    "vi": "Tham gia với chúng tôi",
    "no": "Bli med"
  },
  "CHURCHES": {
    "en": "CHURCHES",
    "vi": "CÁC HỘI THÁNH",
    "no": "MENIGHETER"
  },
  "Calendar": {
    "en": "Calendar",
    "vi": "Lịch",
    "no": "Kalender"
  },
  "Camps": {
    "en": "Camps",
    "vi": "Các Kì Trại",
    "no": "Leirer"
  },
  "Cell Groups": {
    "en": "Cell Groups",
    "vi": "Nhóm Tế Bào",
    "no": "Cellegrupper"
  },
  "Churches": {
    "en": "Churches",
    "vi": "Hội Thánh",
    "no": "Menigheter"
  },
  "Contact": {
    "en": "Contact",
    "vi": "Liên hệ",
    "no": "Kontakt"
  },
  "Courses": {
    "en": "Courses",
    "vi": "Các Khóa Học",
    "no": "Kurs"
  },
  "Các Khóa Học": {
    "en": "Courses",
    "vi": "Các Khóa Học",
    "no": "Kurs"
  },
  "Các Kì Trại": {
    "en": "Camps",
    "vi": "Các Kì Trại",
    "no": "Leirer"
  },
  "Den Vietnamesiske": {
    "en": "The Vietnamese",
    "vi": "Hội Thánh Baptist",
    "no": "Den vietnamesiske"
  },
  "Den Vietnamesiske Baptistmenigheten i Oslo": {
    "en": "The Vietnamese Baptist Church in Oslo",
    "vi": "Hội Thánh Baptist Việt Nam tại Oslo",
    "no": "Den Vietnamesiske Baptistmenigheten i Oslo"
  },
  "Dokument": {
    "en": "Document",
    "vi": "Tài liệu",
    "no": "Dokument"
  },
  "Du har ulagrede data. Hvis du forlater denne siden nå, kan endringene dine gå tapt.": {
    "en": "You have unsaved data. If you leave this page now, your changes may be lost.",
    "vi": "Bạn có dữ liệu chưa lưu. Nếu bạn rời khỏi trang này bây giờ, các thay đổi của bạn có thể bị mất.",
    "no": "Du har ulagrede data. Hvis du forlater denne siden nå, kan endringene dine gå tapt."
  },
  "Europe": {
    "en": "Europe",
    "vi": "Châu Âu",
    "no": "Europa"
  },
  "Evangelisering": {
    "en": "Evangelism",
    "vi": "Chứng đạo",
    "no": "Evangelisering"
  },
  "Folk": {
    "en": "People",
    "vi": "Mọi người",
    "no": "Folk"
  },
  "Gudstjeneste": {
    "en": "Worship Service",
    "vi": "Buổi thờ phượng",
    "no": "Gudstjeneste"
  },
  "Gudstjenester": {
    "en": "Worship Services",
    "vi": "Các buổi thờ phượng",
    "no": "Gudstjenester"
  },
  "Hendelser": {
    "en": "Events",
    "vi": "Sự kiện",
    "no": "Hendelser"
  },
  "Her er vi": {
    "en": "Here we are",
    "vi": "Đây là chúng tôi",
    "no": "Her er vi"
  },
  "Husgrupper": {
    "en": "Cell groups",
    "vi": "Nhóm Tế Bào",
    "no": "Cellegrupper"
  },
  "Hvem er vi": {
    "en": "Who are we",
    "vi": "Chúng ta là ai",
    "no": "Hvem er vi"
  },
  "ICDP - Nuôi dạy con cái": {
    "en": "ICDP - Parenting",
    "vi": "ICDP - Nuôi dạy con cái",
    "no": "ICDP - Foreldreveiledning"
  },
  "Jobs": {
    "en": "Jobs",
    "vi": "Việc làm",
    "no": "Jobbmuligheter"
  },
  "Join a cell group": {
    "en": "Join a cell group",
    "vi": "Tham gia nhóm tế bào",
    "no": "Bli med i en cellegruppe"
  },
  "Kalender": {
    "en": "Calendar",
    "vi": "Lịch",
    "no": "Kalender"
  },
  "Kommende hendelser": {
    "en": "Upcoming events",
    "vi": "Sự kiện sắp tới",
    "no": "Kommende hendelser"
  },
  "Kontakt": {
    "en": "Contact",
    "vi": "Liên hệ",
    "no": "Kontakt"
  },
  "Kontonummer: 1503.02.07693": {
    "en": "Account number: 1503.02.07693",
    "vi": "Số tài khoản: 1503.02.07693",
    "no": "Kontonummer: 1503.02.07693"
  },
  "Kurs": {
    "en": "Courses",
    "vi": "Các Khóa Học",
    "no": "Kurs"
  },
  "Lectures": {
    "en": "Sermons",
    "vi": "Bài giảng",
    "no": "Undervisning"
  },
  "Legg til eksisterende artikkel": {
    "en": "Add existing article",
    "vi": "Thêm bài viết hiện có",
    "no": "Legg til eksisterende artikkel"
  },
  "Leirer": {
    "en": "Camps",
    "vi": "Các Kì Trại",
    "no": "Leirer"
  },
  "Logg inn": {
    "en": "Log in",
    "vi": "Đăng nhập",
    "no": "Logg inn"
  },
  "Lyd": {
    "en": "Audio",
    "vi": "Âm thanh",
    "no": "Lyd"
  },
  "Medlem": {
    "en": "Member",
    "vi": "Thành viên",
    "no": "Medlem"
  },
  "Medlemmer": {
    "en": "Members",
    "vi": "Thành viên",
    "no": "Medlemmer"
  },
  "Melding": {
    "en": "Message",
    "vi": "Tin nhắn",
    "no": "Melding"
  },
  "Mission": {
    "en": "Mission",
    "vi": "Truyền giáo",
    "no": "Misjon"
  },
  "Nettside": {
    "en": "Website",
    "vi": "Trang web",
    "no": "Nettside"
  },
  "Nettsted": {
    "en": "Website",
    "vi": "Trang web",
    "no": "Nettsted"
  },
  "News": {
    "en": "News",
    "vi": "Tin tức",
    "no": "Nyheter"
  },
  "Newsfeed": {
    "en": "Newsfeed",
    "vi": "Bảng tin",
    "no": "Nyhetsstrøm"
  },
  "Nhut Hoang Nguyen": {
    "en": "Nhut Hoang Nguyen",
    "vi": "Nhut Hoang Nguyen",
    "no": "Nhut Hoang Nguyen"
  },
  "Nyheter": {
    "en": "News",
    "vi": "Tin tức",
    "no": "Nyheter"
  },
  "Nyhetsstrøm": {
    "en": "News feed",
    "vi": "Bảng tin",
    "no": "Nyhetsstrøm"
  },
  "OM OSS": {
    "en": "ABOUT US",
    "vi": "VỀ CHÚNG TÔI",
    "no": "OM OSS"
  },
  "Opprett ny artikkel": {
    "en": "Create new article",
    "vi": "Tạo bài viết mới",
    "no": "Opprett ny artikkel"
  },
  "Organisasjonsnummer: 987.10.4554": {
    "en": "Organization number: 987.10.4554",
    "vi": "Số tổ chức: 987.10.4554",
    "no": "Organisasjonsnummer: 987.10.4554"
  },
  "Organization number: 987.10.4554": {
    "en": "Organization number: 987.10.4554",
    "vi": "Số tổ chức: 987.10.4554",
    "no": "Organisasjonsnummer: 987.10.4554"
  },
  "Oslo": {
    "en": "Oslo",
    "vi": "Oslo",
    "no": "Oslo"
  },
  "Oslo Gospel Center": {
    "en": "Oslo Gospel Center",
    "vi": "Oslo Gospel Center",
    "no": "Oslo Gospel Center"
  },
  "Our <strong>cell groups</strong> bring together brothers and sisters in faith who live near each other in the <strong>Oslo, Ski, and Brumunddal</strong> areas. To foster a safe, warm environment where everyone is seen and cared for, each group generally consists of 5 to 10 people.": {
    "en": "Our <strong>cell groups</strong> bring together brothers and sisters in faith who live near each other in the <strong>Oslo, Ski, and Brumunddal</strong> areas. To foster a safe, warm environment where everyone is seen and cared for, each group generally consists of 5 to 10 people.",
    "vi": "Các <strong>nhóm tế bào</strong> của chúng tôi quy tụ anh chị em trong đức tin sống gần nhau tại các khu vực <strong>Oslo, Ski và Brumunddal</strong>. Để nuôi dưỡng một môi trường an toàn, ấm áp nơi mọi người đều được nhìn thấy và quan tâm, mỗi nhóm thường bao gồm từ 5 đến 10 người.",
    "no": "Våre <strong>cellegrupper</strong> samler brødre og søstre i tro som bor nær hverandre i <strong>Oslo, Ski og Brumunddal</strong>-områdene. For å fremme et trygt, varmt miljø der alle blir sett og tatt vare på, består hver gruppe vanligvis av 5 til 10 personer."
  },
  "Our fellowship extends beyond these regular gatherings; we take turns opening our homes to visit one another. The goal of our cell groups is to build a true <strong>spiritual family</strong> – a place where we pray for, support, encourage, and comfort one another in our daily lives, just like siblings under the same roof.": {
    "en": "Our fellowship extends beyond these regular gatherings; we take turns opening our homes to visit one another. The goal of our cell groups is to build a true <strong>spiritual family</strong> – a place where we pray for, support, encourage, and comfort one another in our daily lives, just like siblings under the same roof.",
    "vi": "Sự tương giao của chúng tôi vượt ra ngoài những buổi nhóm họp thường xuyên này; chúng tôi thay phiên nhau mở cửa nhà để thăm viếng lẫn nhau. Mục tiêu của các nhóm tế bào là xây dựng một <strong>gia đình thuộc linh</strong> đích thực – một nơi chúng tôi cầu nguyện cho, hỗ trợ, khích lệ và an ủi lẫn nhau trong cuộc sống hàng ngày, giống như anh chị em ruột dưới cùng một mái nhà.",
    "no": "Vårt fellesskap strekker seg utover disse faste samlingene; vi bytter på å åpne hjemmene våre for å besøke hverandre. Målet med våre cellegrupper er å bygge en ekte <strong>åndelig familie</strong> – et sted der vi ber for, støtter, oppmuntrer og trøster hverandre i hverdagen, akkurat som søsken under samme tak."
  },
  "Rediger artikkel": {
    "en": "Edit article",
    "vi": "Chỉnh sửa bài viết",
    "no": "Rediger artikkel"
  },
  "Register Form": {
    "en": "Register Form",
    "vi": "Mẫu đăng ký",
    "no": "Registreringsskjema"
  },
  "Se flere hendelser": {
    "en": "See more events",
    "vi": "Xem thêm sự kiện",
    "no": "Se flere hendelser"
  },
  "Skjema": {
    "en": "Form",
    "vi": "Biểu mẫu",
    "no": "Skjema"
  },
  "Skjemaer": {
    "en": "Forms",
    "vi": "Biểu mẫu",
    "no": "Skjemaer"
  },
  "Slett artikkel": {
    "en": "Delete article",
    "vi": "Xóa bài viết",
    "no": "Slett artikkel"
  },
  "Slipp her": {
    "en": "Drop here",
    "vi": "Thả vào đây",
    "no": "Slipp her"
  },
  "Study Abroad": {
    "en": "Study Abroad",
    "vi": "Du học",
    "no": "Utenlandsstudier"
  },
  "Tema": {
    "en": "Theme",
    "vi": "Chủ đề",
    "no": "Tema"
  },
  "Temaer": {
    "en": "Topics",
    "vi": "Chủ đề",
    "no": "Temaer"
  },
  "Tilgjengelige roller": {
    "en": "Available roles",
    "vi": "Vai trò có sẵn",
    "no": "Tilgjengelige roller"
  },
  "Topics": {
    "en": "Topics",
    "vi": "Chủ đề",
    "no": "Temaer"
  },
  "Training": {
    "en": "Training",
    "vi": "Đào tạo",
    "no": "Opplæring"
  },
  "Truyền giáo": {
    "en": "Evangelism",
    "vi": "Chứng đạo",
    "no": "Evangelisering"
  },
  "Ungdom": {
    "en": "Youth",
    "vi": "Thanh niên",
    "no": "Ungdom"
  },
  "Velg ditt nye profilbilde": {
    "en": "Choose your new profile picture",
    "vi": "Chọn ảnh đại diện mới của bạn",
    "no": "Velg ditt nye profilbilde"
  },
  "Vi ønsker deg velkommen til våre samlinger. Vi ønsker å være et åpent og inkluderende fellesskap.": {
    "en": "We welcome you to our gatherings. We want to be an open and inclusive community.",
    "vi": "Chúng tôi chào mừng bạn đến với các buổi nhóm họp của chúng tôi. Chúng tôi mong muốn trở thành một cộng đồng cởi mở và hòa nhập.",
    "no": "Vi ønsker deg velkommen til våre samlinger. Vi ønsker å være et åpent og inkluderende fellesskap."
  },
  "Video": {
    "en": "Video",
    "vi": "Video",
    "no": "Video"
  },
  "Videoer": {
    "en": "Videos",
    "vi": "Video",
    "no": "Videoer"
  },
  "Vietnamesisk språkkurs(Khóa học tiếng Việt)": {
    "en": "Vietnamese language course",
    "vi": "Khóa học tiếng Việt",
    "no": "Vietnamesisk språkkurs (Khóa học tiếng Việt)"
  },
  "Vipps: 113470<br> &nbsp;": {
    "en": "Vipps: 113470<br> &nbsp;",
    "vi": "Vipps: 113470<br> &nbsp;",
    "no": "Vipps: 113470<br> &nbsp;"
  },
  "Vision": {
    "en": "Vision",
    "vi": "Tầm nhìn",
    "no": "Visjon"
  },
  "Visjoner og verdier": {
    "en": "Visions and values",
    "vi": "Tầm nhìn và giá trị",
    "no": "Visjoner og verdier"
  },
  "We usually gather on a set evening – often on Saturdays, or at a time that best suits the group members. This is a precious time where we share our lives, study the Bible together, and grow in faith.": {
    "en": "We usually gather on a set evening – often on Saturdays, or at a time that best suits the group members. This is a precious time where we share our lives, study the Bible together, and grow in faith.",
    "vi": "Chúng tôi thường nhóm họp vào một buổi tối cố định – thường là vào thứ Bảy, hoặc vào thời điểm phù hợp nhất với các thành viên trong nhóm. Đây là khoảng thời gian quý báu để chúng tôi chia sẻ cuộc sống, cùng nhau học Kinh Thánh và tăng trưởng trong đức tin.",
    "no": "Vi samles vanligvis på en fast kveld – ofte på lørdager, eller på et tidspunkt som passer best for gruppemedlemmene. Dette er en dyrebar tid hvor vi deler livene våre, studerer Bibelen sammen og vokser i troen."
  },
  "Welcome to our spiritual family": {
    "en": "Welcome to our spiritual family",
    "vi": "Chào mừng đến với gia đình thuộc linh của chúng tôi",
    "no": "Velkommen til vår åndelige familie"
  },
  "eller": {
    "en": "or",
    "vi": "hoặc",
    "no": "eller"
  },
  "fredag": {
    "en": "Friday",
    "vi": "Thứ Sáu",
    "no": "fredag"
  },
  "gospelcenter.oslo@gmail.com": {
    "en": "gospelcenter.oslo@gmail.com",
    "vi": "gospelcenter.oslo@gmail.com",
    "no": "gospelcenter.oslo@gmail.com"
  },
  "velg fil": {
    "en": "select file",
    "vi": "chọn tệp",
    "no": "velg fil"
  }
};
