// Auto-generated by translate-gemini.js. KHÔNG sửa tay — chỉnh strings/*.json rồi chạy lại.
window.WIDGET_TRANSLATIONS = {
  "971 45 443<br> &nbsp;": {
    "vi": "971 45 443<br> &nbsp;",
    "no": "971 45 443<br> &nbsp;",
    "en": "971 45 443<br> &nbsp;"
  },
  "<b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo": {
    "vi": "<b>Địa chỉ</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "no": "<b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo",
    "en": "<b>Address</b><br> Ravnåsveien 3<br> 1254 Oslo"
  },
  "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;": {
    "vi": "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;",
    "no": "<span><a href=\"mailto:gospelcenter.oslo@gmail.com\">gospelcenter.oslo@gmail.com</a></span><br> &nbsp;"
  },
  "<span><b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo</span>": {
    "vi": "<span><b>Địa chỉ</b><br> Ravnåsveien 3<br> 1254 Oslo</span>",
    "no": "<span><b>Adresse</b><br> Ravnåsveien 3<br> 1254 Oslo</span>",
    "en": "<span><b>Address</b><br> Ravnåsveien 3<br> 1254 Oslo</span>"
  },
  "<span>Artikkel</span><span>Artikkel</span>": {
    "vi": "<span>Bài viết</span><span>Bài viết</span>",
    "no": "<span>Artikkel</span><span>Artikkel</span>"
  },
  "<span>Artikkelliste</span><span>Artikkel</span>": {
    "vi": "<span>Danh sách bài viết</span><span>Bài viết</span>",
    "no": "<span>Artikkelliste</span><span>Artikkel</span>"
  },
  "<span>Bilde</span>": {
    "vi": "<span>Ảnh</span>",
    "no": "<span>Bilde</span>"
  },
  "<span>Galleribilder</span>": {
    "vi": "<span>Ảnh thư viện</span>",
    "no": "<span>Galleribilder</span>"
  },
  "<span>Tilgjengelige roller</span>": {
    "vi": "<span>Vai trò có sẵn</span>",
    "no": "<span>Tilgjengelige roller</span>"
  },
  "About Us": {
    "vi": "Về chúng tôi",
    "no": "Om oss"
  },
  "Activities": {
    "vi": "Hoạt động",
    "no": "Aktiviteter"
  },
  "Administrator": {
    "vi": "Quản trị viên",
    "no": "Administrator"
  },
  "Artikkel": {
    "vi": "Bài viết",
    "no": "Artikkel"
  },
  "Betaling": {
    "vi": "Thanh toán",
    "no": "Betaling"
  },
  "Bilde": {
    "vi": "Hình ảnh",
    "no": "Bilde"
  },
  "CHURCHES": {
    "vi": "CÁC HỘI THÁNH",
    "no": "KIRKER"
  },
  "Camps": {
    "vi": "Trại",
    "no": "Leirer"
  },
  "Cell Groups": {
    "vi": "Nhóm Tế Bào",
    "no": "Cellegrupper"
  },
  "Churches": {
    "vi": "Hội Thánh",
    "no": "Kirker"
  },
  "Courses": {
    "vi": "Khóa học",
    "no": "Kurs"
  },
  "Den Vietnamesiske Baptistmenigheten i Oslo": {
    "vi": "Hội thánh Baptist Việt Nam tại Oslo",
    "no": "Den Vietnamesiske Baptistmenigheten i Oslo"
  },
  "Dokument": {
    "vi": "Tài liệu",
    "no": "Dokument"
  },
  "Endre": {
    "vi": "Thay đổi",
    "no": "Endre"
  },
  "English": {
    "vi": "Tiếng Anh",
    "no": "Engelsk"
  },
  "Folk": {
    "vi": "Mọi người",
    "no": "Folk"
  },
  "Husgrupper": {
    "vi": "Nhóm tại gia",
    "no": "Husgrupper",
    "en": "Cell groups"
  },
  "Jobs": {
    "vi": "Việc làm",
    "no": "Jobber"
  },
  "Join a cell group": {
    "vi": "Tham gia một nhóm nhỏ",
    "no": "Bli med i en cellegruppe"
  },
  "Kalender": {
    "vi": "Lịch",
    "no": "Kalender"
  },
  "Kontakt": {
    "vi": "Liên hệ",
    "no": "Kontakt",
    "en": "Contact"
  },
  "Kontonummer: 1503.02.07693": {
    "vi": "Số tài khoản: 1503.02.07693",
    "no": "Kontonummer: 1503.02.07693",
    "en": "Account number: 1503.02.07693"
  },
  "Languages": {
    "vi": "Ngôn ngữ",
    "no": "Språk"
  },
  "Lectures": {
    "vi": "Bài giảng",
    "no": "Forelesninger"
  },
  "Legg til eksisterende artikkel": {
    "vi": "Thêm bài viết hiện có",
    "no": "Legg til eksisterende artikkel"
  },
  "Legg til eksisterende bilde": {
    "vi": "Thêm vào ảnh hiện có",
    "no": "Legg til eksisterende bilde"
  },
  "Legg til nytt bilde": {
    "vi": "Thêm ảnh mới",
    "no": "Legg til nytt bilde"
  },
  "Lyd": {
    "vi": "Âm thanh",
    "no": "Lyd"
  },
  "Medlemmer": {
    "vi": "Thành viên",
    "no": "Medlemmer"
  },
  "Melding": {
    "vi": "Tin nhắn",
    "no": "Melding"
  },
  "Mission": {
    "vi": "Sứ mạng",
    "no": "Misjon"
  },
  "Nettside": {
    "vi": "Trang",
    "no": "Nettside"
  },
  "Nettsted": {
    "vi": "Trang web",
    "no": "Nettsted"
  },
  "News": {
    "vi": "Tin tức",
    "no": "Nyheter"
  },
  "Newsfeed": {
    "vi": "Bảng tin",
    "no": "Nyhetsstrøm"
  },
  "Nhut Hoang Nguyen": {
    "vi": "Nhut Hoang Nguyen",
    "no": "Nhut Hoang Nguyen"
  },
  "Opprett ny artikkel": {
    "vi": "Tạo bài viết mới",
    "no": "Opprett ny artikkel"
  },
  "Organisasjonsnummer: 987.10.4554": {
    "vi": "Số tổ chức: 987.10.4554",
    "no": "Organisasjonsnummer: 987.10.4554",
    "en": "Organization number: 987.10.4554"
  },
  "Our <strong>cell groups</strong> bring together brothers and sisters in faith who live near each other in the <strong>Oslo, Ski, and Brumunddal</strong> areas. To foster a safe, warm environment where everyone is seen and cared for, each group generally consists of 5 to 10 people.": {
    "vi": "<strong>Nhóm nhỏ</strong> của chúng tôi quy tụ anh chị em cùng đức tin sống gần nhau tại các khu vực <strong>Oslo, Ski và Brumunddal</strong>. Để nuôi dưỡng một môi trường an toàn, ấm áp nơi mọi người đều được nhìn nhận và quan tâm, mỗi nhóm thường bao gồm từ 5 đến 10 người.",
    "no": "Våre <strong>celle-grupper</strong> samler brødre og søstre i troen som bor nær hverandre i <strong>Oslo, Ski og Brumunddal</strong>-områdene. For å fremme et trygt, varmt miljø der alle blir sett og tatt vare på, består hver gruppe vanligvis av 5 til 10 personer."
  },
  "Our fellowship extends beyond these regular gatherings; we take turns opening our homes to visit one another. The goal of our cell groups is to build a true <strong>spiritual family</strong> – a place where we pray for, support, encourage, and comfort one another in our daily lives, just like siblings under the same roof.": {
    "vi": "Tình thông công của chúng tôi vượt ra ngoài những buổi nhóm họp thường lệ này; chúng tôi thay phiên nhau mở cửa nhà để thăm viếng lẫn nhau. Mục tiêu của các nhóm nhỏ là xây dựng một <strong>gia đình thuộc linh</strong> đích thực – một nơi chúng tôi cầu nguyện, hỗ trợ, khích lệ và an ủi lẫn nhau trong cuộc sống hàng ngày, giống như anh chị em dưới cùng một mái nhà.",
    "no": "Vårt fellesskap strekker seg utover disse faste samlingene; vi bytter på å åpne hjemmene våre for å besøke hverandre. Målet med våre celle-grupper er å bygge en ekte <strong>åndelig familie</strong> – et sted der vi ber for, støtter, oppmuntrer og trøster hverandre i hverdagen, akkurat som søsken under samme tak."
  },
  "Rediger artikkel": {
    "vi": "Chỉnh sửa bài viết",
    "no": "Rediger artikkel"
  },
  "Rediger bilde": {
    "vi": "Chỉnh sửa ảnh",
    "no": "Rediger bilde"
  },
  "SMS": {
    "vi": "Tin nhắn SMS",
    "no": "SMS"
  },
  "Skjemaer": {
    "vi": "Biểu mẫu",
    "no": "Skjemaer"
  },
  "Slett artikkel": {
    "vi": "Xóa bài viết",
    "no": "Slett artikkel"
  },
  "Slipp her": {
    "vi": "Thả vào đây",
    "no": "Slipp her"
  },
  "Study Abroad": {
    "vi": "Du học",
    "no": "Studere i utlandet"
  },
  "Topics": {
    "vi": "Chủ đề",
    "no": "Emner"
  },
  "Training": {
    "vi": "Đào tạo",
    "no": "Trening"
  },
  "Velg ditt nye profilbilde": {
    "vi": "Chọn ảnh đại diện mới của bạn",
    "no": "Velg ditt nye profilbilde"
  },
  "Video": {
    "vi": "Video",
    "no": "Video"
  },
  "Vipps: 113470<br> &nbsp;": {
    "vi": "Vipps: 113470<br> &nbsp;",
    "no": "Vipps: 113470<br> &nbsp;",
    "en": "Vipps: 113470<br> &nbsp;"
  },
  "Vision": {
    "vi": "Tầm nhìn",
    "no": "Visjon"
  },
  "We usually gather on a set evening – often on Saturdays, or at a time that best suits the group members. This is a precious time where we share our lives, study the Bible together, and grow in faith.": {
    "vi": "Chúng tôi thường nhóm họp vào một buổi tối cố định – thường là vào thứ Bảy, hoặc vào thời điểm phù hợp nhất với các thành viên trong nhóm. Đây là khoảng thời gian quý báu để chúng tôi chia sẻ cuộc sống, cùng nhau học Kinh Thánh và phát triển đức tin.",
    "no": "Vi samles vanligvis på en fast kveld – ofte på lørdager, eller til et tidspunkt som passer best for gruppemedlemmene. Dette er en dyrebar tid der vi deler livene våre, studerer Bibelen sammen og vokser i troen."
  },
  "Welcome to our spiritual family": {
    "vi": "Chào mừng đến với gia đình thuộc linh của chúng tôi",
    "no": "Velkommen til vår åndelige familie"
  },
  "eller": {
    "vi": "hoặc",
    "no": "eller"
  },
  "velg fil": {
    "vi": "chọn tệp",
    "no": "velg fil"
  }
};
