// Auto-generated by translate-gemini.js. KHÔNG sửa tay — chỉnh strings/*.json rồi chạy lại.
window.WIDGET_TRANSLATIONS = {
  "Join a cell group": {
    "vi": "Tham gia một nhóm tế bào",
    "no": "Bli med i en cellegruppe"
  },
  "Oslo, Ski, and Brumunddal": {
    "vi": "Oslo, Ski và Brumunddal",
    "no": "Oslo, Ski og Brumunddal"
  },
  "Our": {
    "vi": "Của chúng tôi",
    "no": "Vår"
  },
  "Our fellowship extends beyond these regular gatherings; we take turns opening our homes to visit one another. The goal of our cell groups is to build a true": {
    "vi": "Sự thông công của chúng tôi mở rộng ra ngoài những buổi nhóm thường xuyên này; chúng tôi luân phiên mở cửa nhà để thăm viếng lẫn nhau. Mục tiêu của các nhóm tế bào của chúng tôi là xây dựng một gia đình tâm linh thực sự",
    "no": "Vårt fellesskap strekker seg utover disse faste samlingene; vi bytter på å åpne hjemmene våre for å besøke hverandre. Målet med cellegruppene våre er å bygge en sann"
  },
  "We usually gather on a set evening – often on Saturdays, or at a time that best suits the group members. This is a precious time where we share our lives, study the Bible together, and grow in faith.": {
    "vi": "Chúng tôi thường nhóm lại vào một buổi tối cố định – thường là vào thứ Bảy, hoặc vào thời điểm phù hợp nhất với các thành viên trong nhóm. Đây là thời gian quý báu để chúng tôi chia sẻ cuộc sống, cùng nhau học Kinh Thánh và lớn lên trong đức tin.",
    "no": "Vi samles vanligvis en fast kveld – ofte på lørdager, eller på et tidspunkt som passer best for gruppemedlemmene. Dette er en verdifull tid hvor vi deler livene våre, studerer Bibelen sammen og vokser i tro."
  },
  "Welcome to our spiritual family": {
    "vi": "Chào mừng đến với gia đình tâm linh của chúng tôi",
    "no": "Velkommen til vår åndelige familie"
  },
  "areas. To foster a safe, warm environment where everyone is seen and cared for, each group generally consists of 5 to 10 people.": {
    "vi": "khu vực. Để tạo ra một môi trường an toàn, ấm áp nơi mọi người được nhìn thấy và quan tâm, mỗi nhóm thường bao gồm 5 đến 10 người.",
    "no": "områder. For å fremme et trygt, varmt miljø der alle blir sett og tatt vare på, består hver gruppe vanligvis av 5 til 10 personer."
  },
  "bring together brothers and sisters in faith who live near each other in the": {
    "vi": "quy tụ anh chị em trong đức tin sống gần nhau trong các",
    "no": "samler brødre og søstre i tro som bor nær hverandre i"
  },
  "cell groups": {
    "vi": "nhóm tế bào",
    "no": "cellegrupper"
  },
  "spiritual family": {
    "vi": "gia đình tâm linh",
    "no": "åndelig familie"
  },
  "– a place where we pray for, support, encourage, and comfort one another in our daily lives, just like siblings under the same roof.": {
    "vi": "– một nơi chúng ta cầu nguyện, hỗ trợ, khích lệ và an ủi lẫn nhau trong cuộc sống hàng ngày, giống như anh chị em ruột dưới cùng một mái nhà.",
    "no": "– et sted hvor vi ber for, støtter, oppmuntrer og trøster hverandre i våre daglige liv, akkurat som søsken under samme tak."
  },
  "About Us": {
    "vi": "Về chúng tôi",
    "no": "Om oss"
  },
  "Activities": {
    "vi": "Hoạt động",
    "no": "Aktiviteter"
  },
  "Administrator": {
    "vi": "Quản trị viên",
    "no": "Administrator"
  },
  "CHURCHES": {
    "vi": "CÁC HỘI THÁNH",
    "no": "KIRKER"
  },
  "Camps": {
    "vi": "Trại",
    "no": "Leirer"
  },
  "Cell Groups": {
    "vi": "Nhóm Tế Bào",
    "no": "Cellegrupper"
  },
  "Churches": {
    "vi": "Hội Thánh",
    "no": "Kirker"
  },
  "Courses": {
    "vi": "Khóa học",
    "no": "Kurs"
  },
  "English": {
    "vi": "Tiếng Anh",
    "no": "Engelsk"
  },
  "Jobs": {
    "vi": "Việc làm",
    "no": "Jobber"
  },
  "Languages": {
    "vi": "Ngôn ngữ",
    "no": "Språk"
  },
  "Lectures": {
    "vi": "Bài giảng",
    "no": "Forelesninger"
  },
  "Mission": {
    "vi": "Sứ mạng",
    "no": "Misjon"
  },
  "News": {
    "vi": "Tin tức",
    "no": "Nyheter"
  },
  "Newsfeed": {
    "vi": "Bảng tin",
    "no": "Nyhetsstrøm"
  },
  "SMS": {
    "vi": "Tin nhắn SMS",
    "no": "SMS"
  },
  "Study Abroad": {
    "vi": "Du học",
    "no": "Studere i utlandet"
  },
  "Topics": {
    "vi": "Chủ đề",
    "no": "Emner"
  },
  "Training": {
    "vi": "Đào tạo",
    "no": "Trening"
  },
  "Video": {
    "vi": "Video",
    "no": "Video"
  },
  "Vision": {
    "vi": "Tầm nhìn",
    "no": "Visjon"
  }
};
